name: my_game_flutter
description: A new Flutter project with Serverpod.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '^3.8.0'
  flutter: '^3.32.0'

resolution: workspace

dependencies:
  fast_noise: ^2.0.0
  flame: ^1.35.1
  flame_splash_screen: ^0.3.1+2
  flame_tiled: ^3.0.11
  flutter:
    sdk: flutter
  my_game_client:
    path: ../my_game_client
  serverpod_auth_idp_flutter: 3.3.1
  serverpod_flutter: 3.3.1

dev_dependencies:
  flutter_lints: '>=3.0.0 <7.0.0'
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/config.json
    - assets/images/
