services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: my_game
      POSTGRES_PASSWORD: "yKToQmE7aqOs-HLc0IBFLwE5cjTaE6dZ"
    volumes:
      - my_game_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "Cb6h1OqERu-Vylsc1Kqg9t9PlmgxfdfH"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: my_game_test
      POSTGRES_PASSWORD: "aLG8WOb4k56_b23SrG8bWxI1cFl6nRj2"
    volumes:
      - my_game_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "2eCHmUP79_GLfsu0xuIf7KiPWADnSSme"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  my_game_data:
  my_game_test_data:
